// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#include <string.h>
#include "balancebot_msg_t.h"

static int __balancebot_msg_t_hash_computed;
static uint64_t __balancebot_msg_t_hash;

uint64_t __balancebot_msg_t_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __balancebot_msg_t_get_hash)
            return 0;

    __lcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = (void*)__balancebot_msg_t_get_hash;
    (void) cp;

    uint64_t hash = (uint64_t)0xa7df6edc1e9740f9LL
         + __int64_t_hash_recursive(&cp)
         + __pose_xyt_t_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
         + __balancebot_gate_t_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __balancebot_msg_t_get_hash(void)
{
    if (!__balancebot_msg_t_hash_computed) {
        __balancebot_msg_t_hash = (int64_t)__balancebot_msg_t_hash_recursive(NULL);
        __balancebot_msg_t_hash_computed = 1;
    }

    return __balancebot_msg_t_hash;
}

int __balancebot_msg_t_encode_array(void *buf, int offset, int maxlen, const balancebot_msg_t *p, int elements)
{
    int pos = 0, element;
    int thislen;

    for (element = 0; element < elements; element++) {

        thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].utime), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __pose_xyt_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].pose), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].num_gates), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __balancebot_gate_t_encode_array(buf, offset + pos, maxlen - pos, p[element].gates, p[element].num_gates);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int balancebot_msg_t_encode(void *buf, int offset, int maxlen, const balancebot_msg_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __balancebot_msg_t_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __balancebot_msg_t_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int __balancebot_msg_t_encoded_array_size(const balancebot_msg_t *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {

        size += __int64_t_encoded_array_size(&(p[element].utime), 1);

        size += __pose_xyt_t_encoded_array_size(&(p[element].pose), 1);

        size += __int16_t_encoded_array_size(&(p[element].num_gates), 1);

        size += __balancebot_gate_t_encoded_array_size(p[element].gates, p[element].num_gates);

    }
    return size;
}

int balancebot_msg_t_encoded_size(const balancebot_msg_t *p)
{
    return 8 + __balancebot_msg_t_encoded_array_size(p, 1);
}

size_t balancebot_msg_t_struct_size(void)
{
    return sizeof(balancebot_msg_t);
}

int balancebot_msg_t_num_fields(void)
{
    return 4;
}

int balancebot_msg_t_get_field(const balancebot_msg_t *p, int i, lcm_field_t *f)
{
    if (0 > i || i >= balancebot_msg_t_num_fields())
        return 1;
    
    switch (i) {
    
        case 0: {
            f->name = "utime";
            f->type = LCM_FIELD_INT64_T;
            f->typestr = "int64_t";
            f->num_dim = 0;
            f->data = (void *) &p->utime;
            return 0;
        }
        
        case 1: {
            /* pose_xyt_t */
            f->name = "pose";
            f->type = LCM_FIELD_USER_TYPE;
            f->typestr = "pose_xyt_t";
            f->num_dim = 0;
            f->data = (void *) &p->pose;
            return 0;
        }
        
        case 2: {
            f->name = "num_gates";
            f->type = LCM_FIELD_INT16_T;
            f->typestr = "int16_t";
            f->num_dim = 0;
            f->data = (void *) &p->num_gates;
            return 0;
        }
        
        case 3: {
            /* balancebot_gate_t */
            f->name = "gates";
            f->type = LCM_FIELD_USER_TYPE;
            f->typestr = "balancebot_gate_t";
            f->num_dim = 1;
            f->dim_size[0] = p->num_gates;
            f->dim_is_variable[0] = 1;
            f->data = (void *) &p->gates;
            return 0;
        }
        
        default:
            return 1;
    }
}

const lcm_type_info_t *balancebot_msg_t_get_type_info(void)
{
    static int init = 0;
    static lcm_type_info_t typeinfo;
    if (!init) {
        typeinfo.encode         = (lcm_encode_t) balancebot_msg_t_encode;
        typeinfo.decode         = (lcm_decode_t) balancebot_msg_t_decode;
        typeinfo.decode_cleanup = (lcm_decode_cleanup_t) balancebot_msg_t_decode_cleanup;
        typeinfo.encoded_size   = (lcm_encoded_size_t) balancebot_msg_t_encoded_size;
        typeinfo.struct_size    = (lcm_struct_size_t)  balancebot_msg_t_struct_size;
        typeinfo.num_fields     = (lcm_num_fields_t) balancebot_msg_t_num_fields;
        typeinfo.get_field      = (lcm_get_field_t) balancebot_msg_t_get_field;
        typeinfo.get_hash       = (lcm_get_hash_t) __balancebot_msg_t_get_hash;
    }
    
    return &typeinfo;
}
int __balancebot_msg_t_decode_array(const void *buf, int offset, int maxlen, balancebot_msg_t *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].utime), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __pose_xyt_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].pose), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].num_gates), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        p[element].gates = (balancebot_gate_t*) lcm_malloc(sizeof(balancebot_gate_t) * p[element].num_gates);
        thislen = __balancebot_gate_t_decode_array(buf, offset + pos, maxlen - pos, p[element].gates, p[element].num_gates);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __balancebot_msg_t_decode_array_cleanup(balancebot_msg_t *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int64_t_decode_array_cleanup(&(p[element].utime), 1);

        __pose_xyt_t_decode_array_cleanup(&(p[element].pose), 1);

        __int16_t_decode_array_cleanup(&(p[element].num_gates), 1);

        __balancebot_gate_t_decode_array_cleanup(p[element].gates, p[element].num_gates);
        if (p[element].gates) free(p[element].gates);

    }
    return 0;
}

int balancebot_msg_t_decode(const void *buf, int offset, int maxlen, balancebot_msg_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __balancebot_msg_t_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __balancebot_msg_t_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int balancebot_msg_t_decode_cleanup(balancebot_msg_t *p)
{
    return __balancebot_msg_t_decode_array_cleanup(p, 1);
}

int __balancebot_msg_t_clone_array(const balancebot_msg_t *p, balancebot_msg_t *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int64_t_clone_array(&(p[element].utime), &(q[element].utime), 1);

        __pose_xyt_t_clone_array(&(p[element].pose), &(q[element].pose), 1);

        __int16_t_clone_array(&(p[element].num_gates), &(q[element].num_gates), 1);

        q[element].gates = (balancebot_gate_t*) lcm_malloc(sizeof(balancebot_gate_t) * q[element].num_gates);
        __balancebot_gate_t_clone_array(p[element].gates, q[element].gates, p[element].num_gates);

    }
    return 0;
}

balancebot_msg_t *balancebot_msg_t_copy(const balancebot_msg_t *p)
{
    balancebot_msg_t *q = (balancebot_msg_t*) malloc(sizeof(balancebot_msg_t));
    __balancebot_msg_t_clone_array(p, q, 1);
    return q;
}

void balancebot_msg_t_destroy(balancebot_msg_t *p)
{
    __balancebot_msg_t_decode_array_cleanup(p, 1);
    free(p);
}

int balancebot_msg_t_publish(lcm_t *lc, const char *channel, const balancebot_msg_t *p)
{
      int max_data_size = balancebot_msg_t_encoded_size (p);
      uint8_t *buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = balancebot_msg_t_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = lcm_publish (lc, channel, buf, data_size);
      free (buf);
      return status;
}

struct _balancebot_msg_t_subscription_t {
    balancebot_msg_t_handler_t user_handler;
    void *userdata;
    lcm_subscription_t *lc_h;
};
static
void balancebot_msg_t_handler_stub (const lcm_recv_buf_t *rbuf,
                            const char *channel, void *userdata)
{
    int status;
    balancebot_msg_t p;
    memset(&p, 0, sizeof(balancebot_msg_t));
    status = balancebot_msg_t_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding balancebot_msg_t!!!\n", status);
        return;
    }

    balancebot_msg_t_subscription_t *h = (balancebot_msg_t_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    balancebot_msg_t_decode_cleanup (&p);
}

balancebot_msg_t_subscription_t* balancebot_msg_t_subscribe (lcm_t *lcm,
                    const char *channel,
                    balancebot_msg_t_handler_t f, void *userdata)
{
    balancebot_msg_t_subscription_t *n = (balancebot_msg_t_subscription_t*)
                       malloc(sizeof(balancebot_msg_t_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->lc_h = lcm_subscribe (lcm, channel,
                                 balancebot_msg_t_handler_stub, n);
    if (n->lc_h == NULL) {
        fprintf (stderr,"couldn't reg balancebot_msg_t LCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int balancebot_msg_t_subscription_set_queue_capacity (balancebot_msg_t_subscription_t* subs,
                              int num_messages)
{
    return lcm_subscription_set_queue_capacity (subs->lc_h, num_messages);
}

int balancebot_msg_t_unsubscribe(lcm_t *lcm, balancebot_msg_t_subscription_t* hid)
{
    int status = lcm_unsubscribe (lcm, hid->lc_h);
    if (0 != status) {
        fprintf(stderr,
           "couldn't unsubscribe balancebot_msg_t_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

